# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gmail}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["BehindLogic", "Kriss 'nu7hatch' Kowalik"]
  s.date = %q{2010-10-20}
  s.description = %q{      A Rubyesque interface to Gmail, with all the tools you'll need. Search, 
      read and send multipart emails; archive, mark as read/unread, delete emails; 
      and manage labels.
}
  s.email = %q{kriss.kowalik@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG.md",
     "LICENSE",
     "README.md",
     "Rakefile",
     "TODO.md",
     "VERSION",
     "lib/gmail.rb",
     "lib/gmail/client.rb",
     "lib/gmail/labels.rb",
     "lib/gmail/mailbox.rb",
     "lib/gmail/message.rb",
     "lib/gmail/version.rb",
     "spec/client_spec.rb",
     "spec/gmail_spec.rb",
     "spec/mailbox_spec.rb",
     "spec/message_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/nu7hatch/gmail}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Rubyesque interface to Gmail, with all the tools you'll need.}
  s.test_files = [
    "spec/message_spec.rb",
     "spec/mailbox_spec.rb",
     "spec/spec_helper.rb",
     "spec/client_spec.rb",
     "spec/gmail_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mime>, [">= 0.1"])
      s.add_runtime_dependency(%q<mail>, [">= 2.2.1"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
      s.add_development_dependency(%q<mocha>, [">= 0.9"])
    else
      s.add_dependency(%q<mime>, [">= 0.1"])
      s.add_dependency(%q<mail>, [">= 2.2.1"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
      s.add_dependency(%q<mocha>, [">= 0.9"])
    end
  else
    s.add_dependency(%q<mime>, [">= 0.1"])
    s.add_dependency(%q<mail>, [">= 2.2.1"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
    s.add_dependency(%q<mocha>, [">= 0.9"])
  end
end

